/**
 * Pure Markdown formatters for GitHub PR comments and check-run summaries.
 */

export const DEFAULT_DASHBOARD_URL = 'http://localhost:3002';
export const MAX_TABLE_FINDINGS = 10;

export interface FormattedFinding {
  id?: string;
  type: string;
  severity: string;
  title: string;
  description: string;
  filePath: string;
  lineStart: number;
  lineEnd?: number;
  codeSnippet?: string | null;
}

export interface CommentMeta {
  analysisId: string;
  model: string;
  confidence: number;
  llmTier1Calls: number;
  llmTier2Calls: number;
  estimatedCost: number;
  prNumber?: number;
  dashboardBaseUrl?: string;
}

export type FindingCategory = 'security' | 'quality';

const SECURITY_TYPES = new Set(['hallucination', 'security']);
const HIGH_SEVERITIES = new Set(['high', 'critical']);

export function getDashboardBaseUrl(baseUrl?: string): string {
  const raw = baseUrl ?? process.env.VOUCH_DASHBOARD_URL ?? DEFAULT_DASHBOARD_URL;
  return raw.replace(/\/+$/, '');
}

export function buildFindingDetailUrl(
  finding: FormattedFinding,
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string {
  const base = getDashboardBaseUrl(meta.dashboardBaseUrl);
  const params = new URLSearchParams();
  if (meta.prNumber !== undefined) {
    params.set('pr', String(meta.prNumber));
  }
  if (finding.id) {
    params.set('finding', finding.id);
  }
  const qs = params.toString();
  return qs ? `${base}/findings?${qs}` : `${base}/findings`;
}

export function classifyFinding(finding: FormattedFinding): FindingCategory {
  if (finding.type === 'anti-pattern') {
    return 'quality';
  }
  if (SECURITY_TYPES.has(finding.type) || HIGH_SEVERITIES.has(finding.severity.toLowerCase())) {
    return 'security';
  }
  return 'security';
}

export function isBlockingFinding(finding: FormattedFinding): boolean {
  return classifyFinding(finding) === 'security';
}

export function hasBlockingFindings(findings: FormattedFinding[]): boolean {
  return findings.some(isBlockingFinding);
}

export function splitFindings(findings: FormattedFinding[]): {
  security: FormattedFinding[];
  quality: FormattedFinding[];
} {
  const security: FormattedFinding[] = [];
  const quality: FormattedFinding[] = [];

  for (const finding of findings) {
    if (classifyFinding(finding) === 'quality') {
      quality.push(finding);
    } else {
      security.push(finding);
    }
  }

  return { security, quality };
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

function packageOrFileLabel(finding: FormattedFinding): string {
  if (finding.codeSnippet?.trim()) {
    return finding.codeSnippet.trim();
  }
  return `${finding.filePath}:${finding.lineStart}`;
}

function buildTableRows(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string[] {
  return findings.map((finding) => {
    const label = escapeTableCell(packageOrFileLabel(finding));
    const type = escapeTableCell(finding.type);
    const reason = escapeTableCell(finding.title);
    const detailsUrl = buildFindingDetailUrl(finding, meta);
    return `| \`${label}\` | ${type} | ${reason} | [View Details](${detailsUrl}) |`;
  });
}

function renderFindingsTable(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string {
  if (findings.length === 0) {
    return '_No findings in this section._';
  }

  const lines = [
    '| Package/File | Type | Reason | Details |',
    '| --- | --- | --- | --- |',
    ...buildTableRows(findings, meta),
  ];
  return lines.join('\n');
}

function renderTransparencyFooter(model: string): string {
  return [
    '---',
    '',
    `🤖 **AI System Disclosure:** This analysis was generated by Vouch using deterministic AST parsing and **${model}**. Learn more about [how Vouch works](https://github.com/0-uddeshya-0/Vouch).`,
  ].join('\n');
}

export interface FormattedComment {
  markdown: string;
  displayedCount: number;
  totalCount: number;
  truncated: boolean;
}

/**
 * Build PR comment Markdown. Returns `null` when there are no findings (spam prevention).
 */
export function formatPRComment(
  findings: FormattedFinding[],
  meta: CommentMeta
): string | null {
  if (findings.length === 0) {
    return null;
  }

  const totalCount = findings.length;
  const displayed = findings.slice(0, MAX_TABLE_FINDINGS);
  const truncated = totalCount > MAX_TABLE_FINDINGS;
  const remaining = totalCount - displayed.length;

  const { security, quality } = splitFindings(displayed);
  const dashboardUrl = getDashboardBaseUrl(meta.dashboardBaseUrl);

  const lines: string[] = [
    '## Vouch Analysis',
    '',
    `Analysis \`${meta.analysisId}\` · model **${meta.model}** · confidence threshold **${meta.confidence}**`,
    '',
  ];

  if (security.some((f) => f.severity.toLowerCase() === 'critical')) {
    lines.push('> [!CAUTION]', '> Critical security or hallucination issues require attention before merge.', '');
  } else if (security.length > 0) {
    lines.push('> [!WARNING]', '> Security or hallucination findings were detected in this pull request.', '');
  }

  lines.push('### 🚨 Security & Hallucinations', '', renderFindingsTable(security, meta), '');

  if (quality.length > 0) {
    lines.push('> [!NOTE]', '> Dependency quality suggestions are advisory and do not block merge on their own.', '');
  }

  lines.push('### 🧹 Dependency Quality', '', renderFindingsTable(quality, meta), '');

  if (truncated) {
    lines.push(
      `> [!NOTE]`,
      `> ...and **${remaining}** more finding${remaining === 1 ? '' : 's'}. [View the full report on the Vouch Dashboard](${dashboardUrl}/findings${meta.prNumber !== undefined ? `?pr=${meta.prNumber}` : ''}).`,
      ''
    );
  }

  lines.push(renderTransparencyFooter(meta.model));

  return lines.join('\n');
}

export interface CheckRunPresentation {
  title: string;
  summary: string;
  conclusion: 'success' | 'neutral' | 'failure' | 'action_required';
  text: string;
}

export function buildCheckRunPresentation(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'model' | 'analysisId'>
): CheckRunPresentation {
  if (findings.length === 0) {
    return {
      title: 'Vouch found no issues',
      summary: 'No security, hallucination, or dependency quality findings were detected.',
      conclusion: 'success',
      text: 'All checks passed.',
    };
  }

  const { security, quality } = splitFindings(findings);
  const blocking = hasBlockingFindings(findings);

  const hallucinationCount = findings.filter((f) => f.type === 'hallucination').length;
  const securityCount = security.length;

  let title: string;
  if (hallucinationCount > 0) {
    title = `Vouch detected ${hallucinationCount} hallucinated dependenc${hallucinationCount === 1 ? 'y' : 'ies'}`;
  } else if (securityCount > 0) {
    title = `Vouch detected ${securityCount} security issue${securityCount === 1 ? '' : 's'}`;
  } else {
    title = `Vouch flagged ${quality.length} dependency quality suggestion${quality.length === 1 ? '' : 's'}`;
  }

  const summaryParts: string[] = [];
  if (security.length > 0) {
    summaryParts.push(`${security.length} security/hallucination finding${security.length === 1 ? '' : 's'}`);
  }
  if (quality.length > 0) {
    summaryParts.push(`${quality.length} dependency quality suggestion${quality.length === 1 ? '' : 's'}`);
  }

  const summary = `Vouch found ${findings.length} issue${findings.length === 1 ? '' : 's'} (${summaryParts.join(', ')}). Model ${meta.model}.`;

  const textLines = [
    `Analysis ID: ${meta.analysisId}`,
    '',
    ...findings.slice(0, MAX_TABLE_FINDINGS).map(
      (f) => `- **${f.severity}** [${f.type}] ${f.title} (\`${f.filePath}:${f.lineStart}\`)`
    ),
  ];

  if (findings.length > MAX_TABLE_FINDINGS) {
    textLines.push('', `...and ${findings.length - MAX_TABLE_FINDINGS} more finding(s).`);
  }

  return {
    title,
    summary,
    conclusion: blocking ? 'action_required' : 'neutral',
    text: textLines.join('\n'),
  };
}
