/**
 * Pure Markdown formatters for GitHub PR comments and check-run summaries.
 */

import type { GateResult } from '../gate/maintainer-gate';

export const DEFAULT_DASHBOARD_URL = 'http://localhost:3002';
export const MAX_TABLE_FINDINGS = 10;

/** Hidden marker used to find and update Vouch's existing PR comment instead of posting a new one. */
export const VOUCH_COMMENT_MARKER = '<!-- vouch:analysis-comment -->';

export interface FormattedFinding {
  id?: string;
  type: string;
  severity: string;
  title: string;
  description: string;
  filePath: string;
  lineStart: number;
  lineEnd?: number;
  codeSnippet?: string | null;
}

export interface CommentMeta {
  analysisId: string;
  model: string;
  confidence: number;
  llmTier1Calls: number;
  llmTier2Calls: number;
  estimatedCost: number;
  prNumber?: number;
  dashboardBaseUrl?: string;
  gate?: GateResult;
}

export type FindingCategory = 'security' | 'quality';

const SECURITY_TYPES = new Set(['hallucination', 'security']);
const HIGH_SEVERITIES = new Set(['high', 'critical']);

export function getDashboardBaseUrl(baseUrl?: string): string {
  const raw = baseUrl ?? process.env.VOUCH_DASHBOARD_URL ?? DEFAULT_DASHBOARD_URL;
  return raw.replace(/\/+$/, '');
}

export function buildFindingDetailUrl(
  finding: FormattedFinding,
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string {
  const base = getDashboardBaseUrl(meta.dashboardBaseUrl);
  const params = new URLSearchParams();
  if (meta.prNumber !== undefined) {
    params.set('pr', String(meta.prNumber));
  }
  if (finding.id) {
    params.set('finding', finding.id);
  }
  const qs = params.toString();
  return qs ? `${base}/findings?${qs}` : `${base}/findings`;
}

export function classifyFinding(finding: FormattedFinding): FindingCategory {
  if (finding.type === 'anti-pattern') {
    return 'quality';
  }
  if (SECURITY_TYPES.has(finding.type) || HIGH_SEVERITIES.has(finding.severity.toLowerCase())) {
    return 'security';
  }
  return 'security';
}

export function isBlockingFinding(finding: FormattedFinding): boolean {
  return classifyFinding(finding) === 'security';
}

export function hasBlockingFindings(findings: FormattedFinding[]): boolean {
  return findings.some(isBlockingFinding);
}

export function splitFindings(findings: FormattedFinding[]): {
  security: FormattedFinding[];
  quality: FormattedFinding[];
} {
  const security: FormattedFinding[] = [];
  const quality: FormattedFinding[] = [];

  for (const finding of findings) {
    if (classifyFinding(finding) === 'quality') {
      quality.push(finding);
    } else {
      security.push(finding);
    }
  }

  return { security, quality };
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

function packageOrFileLabel(finding: FormattedFinding): string {
  if (finding.codeSnippet?.trim()) {
    return finding.codeSnippet.trim();
  }
  return `${finding.filePath}:${finding.lineStart}`;
}

function buildTableRows(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string[] {
  return findings.map((finding) => {
    const label = escapeTableCell(packageOrFileLabel(finding));
    const type = escapeTableCell(finding.type);
    const reason = escapeTableCell(finding.title);
    const detailsUrl = buildFindingDetailUrl(finding, meta);
    return `| \`${label}\` | ${type} | ${reason} | [View Details](${detailsUrl}) |`;
  });
}

function renderFindingsTable(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'prNumber' | 'dashboardBaseUrl'>
): string {
  if (findings.length === 0) {
    return '_No findings in this section._';
  }

  const lines = [
    '| Package/File | Type | Reason | Details |',
    '| --- | --- | --- | --- |',
    ...buildTableRows(findings, meta),
  ];
  return lines.join('\n');
}

function renderTransparencyFooter(meta: CommentMeta): string {
  const usedLlm = meta.llmTier1Calls + meta.llmTier2Calls > 0;
  const analysisMethod = usedLlm
    ? `deterministic AST parsing and **${meta.model}**`
    : 'deterministic AST parsing and registry verification (no LLM inference on this run)';

  return [
    '---',
    '',
    `🤖 **AI System Disclosure:** This analysis was generated by Vouch using ${analysisMethod}. Learn more about [how Vouch works](https://github.com/0-uddeshya-0/Vouch).`,
  ].join('\n');
}

function selectDisplayedFindings(findings: FormattedFinding[]): {
  security: FormattedFinding[];
  quality: FormattedFinding[];
  truncated: boolean;
  remaining: number;
} {
  const { security, quality } = splitFindings(findings);
  const securityShown = security.slice(0, MAX_TABLE_FINDINGS);
  const slotsLeft = MAX_TABLE_FINDINGS - securityShown.length;
  const qualityShown = slotsLeft > 0 ? quality.slice(0, slotsLeft) : [];
  const displayedCount = securityShown.length + qualityShown.length;

  return {
    security: securityShown,
    quality: qualityShown,
    truncated: findings.length > displayedCount,
    remaining: findings.length - displayedCount,
  };
}

export interface FormattedComment {
  markdown: string;
  displayedCount: number;
  totalCount: number;
  truncated: boolean;
}

const GATE_STATUS_ICON: Record<string, string> = { pass: '✅', fail: '❌', warn: '⚠️' };

function renderGateSection(gate: GateResult): string[] {
  const total = gate.items.length;
  const lines: string[] = [
    `### 🛡️ Maintainer Gate — ${gate.passedCount}/${total} evidence checks passed`,
    '',
  ];

  if (gate.verdict === 'fail') {
    lines.push(
      '> [!CAUTION]',
      '> This pull request has not met the evidence bar for review. Please address the ❌ items below — maintainer review is gated until they pass.',
      ''
    );
  } else if (gate.verdict === 'advisory-fail') {
    lines.push(
      '> [!NOTE]',
      '> Some evidence checks did not pass (advisory for this author).',
      ''
    );
  }

  for (const item of gate.items) {
    lines.push(`- ${GATE_STATUS_ICON[item.status]} **${item.label}** — ${item.detail}`);
  }
  lines.push('');
  return lines;
}

/**
 * Build PR comment Markdown. Returns `null` when there are no findings and the
 * gate fully passed (spam prevention — silence is the reward for clean PRs).
 */
export function formatPRComment(
  findings: FormattedFinding[],
  meta: CommentMeta
): string | null {
  if (findings.length === 0 && (!meta.gate || meta.gate.verdict === 'pass')) {
    return null;
  }

  const totalCount = findings.length;
  const { security, quality, truncated, remaining } = selectDisplayedFindings(findings);
  const dashboardUrl = getDashboardBaseUrl(meta.dashboardBaseUrl);

  const lines: string[] = [
    VOUCH_COMMENT_MARKER,
    '## Vouch Analysis',
    '',
    `Analysis \`${meta.analysisId}\` · model **${meta.model}** · confidence threshold **${meta.confidence}**`,
    '',
  ];

  if (meta.gate) {
    lines.push(...renderGateSection(meta.gate));
  }

  if (security.some((f) => f.severity.toLowerCase() === 'critical')) {
    lines.push('> [!CAUTION]', '> Critical security or hallucination issues require attention before merge.', '');
  } else if (security.length > 0) {
    lines.push('> [!WARNING]', '> Security or hallucination findings were detected in this pull request.', '');
  }

  lines.push('### 🚨 Security & Hallucinations', '');

  if (security.length > 0) {
    lines.push(renderFindingsTable(security, meta), '');
  } else {
    lines.push('_No security or hallucination findings._', '');
  }

  if (quality.length > 0) {
    lines.push('> [!NOTE]', '> Dependency quality suggestions are advisory and do not block merge on their own.', '');
  }

  lines.push('### 🧹 Dependency Quality', '');

  if (quality.length > 0) {
    lines.push(renderFindingsTable(quality, meta), '');
  } else {
    lines.push('_No dependency quality suggestions._', '');
  }

  if (truncated) {
    lines.push(
      `> [!NOTE]`,
      `> ...and **${remaining}** more finding${remaining === 1 ? '' : 's'}. [View the full report on the Vouch Dashboard](${dashboardUrl}/findings${meta.prNumber !== undefined ? `?pr=${meta.prNumber}` : ''}).`,
      ''
    );
  }

  lines.push(renderTransparencyFooter(meta));

  return lines.join('\n');
}

export interface CheckRunPresentation {
  title: string;
  summary: string;
  conclusion: 'success' | 'neutral' | 'failure' | 'action_required';
  text: string;
}

export function buildCheckRunPresentation(
  findings: FormattedFinding[],
  meta: Pick<CommentMeta, 'model' | 'analysisId' | 'gate'>
): CheckRunPresentation {
  const gate = meta.gate;

  // An enforced gate failure overrides everything: the evidence bar was not met.
  if (gate && gate.verdict === 'fail') {
    const failed = gate.items.filter((i) => i.status === 'fail');
    return {
      title: `Evidence gate: ${gate.failedCount} of ${gate.items.length} checks failed`,
      summary:
        `This PR has not met the evidence bar for maintainer review. Failed: ` +
        failed.map((i) => i.label.toLowerCase()).join('; ') +
        '. See the Vouch comment on the PR for what to fix.',
      conclusion: 'action_required',
      text: gate.items
        .map((i) => `- [${i.status === 'pass' ? 'x' : ' '}] ${i.label} — ${i.detail}`)
        .join('\n'),
    };
  }

  if (findings.length === 0) {
    const gateNote =
      gate && gate.items.length > 0
        ? ` Evidence gate passed (${gate.passedCount}/${gate.items.length}).`
        : '';
    return {
      title: 'Vouch found no issues',
      summary: `No security, hallucination, or dependency quality findings were detected.${gateNote}`,
      conclusion: 'success',
      text: 'All checks passed.',
    };
  }

  const { security, quality } = splitFindings(findings);
  const blocking = hasBlockingFindings(findings);

  const hallucinationCount = findings.filter((f) => f.type === 'hallucination').length;
  const securityCount = security.length;

  let title: string;
  if (hallucinationCount > 0) {
    title = `Vouch detected ${hallucinationCount} hallucinated dependenc${hallucinationCount === 1 ? 'y' : 'ies'}`;
  } else if (securityCount > 0) {
    title = `Vouch detected ${securityCount} security issue${securityCount === 1 ? '' : 's'}`;
  } else {
    title = `Vouch flagged ${quality.length} dependency quality suggestion${quality.length === 1 ? '' : 's'}`;
  }

  const summaryParts: string[] = [];
  if (security.length > 0) {
    summaryParts.push(`${security.length} security/hallucination finding${security.length === 1 ? '' : 's'}`);
  }
  if (quality.length > 0) {
    summaryParts.push(`${quality.length} dependency quality suggestion${quality.length === 1 ? '' : 's'}`);
  }

  const summary = `Vouch found ${findings.length} issue${findings.length === 1 ? '' : 's'} (${summaryParts.join(', ')}). Model ${meta.model}.`;

  const textLines = [
    `Analysis ID: ${meta.analysisId}`,
    '',
    ...findings.slice(0, MAX_TABLE_FINDINGS).map(
      (f) => `- **${f.severity}** [${f.type}] ${f.title} (\`${f.filePath}:${f.lineStart}\`)`
    ),
  ];

  if (findings.length > MAX_TABLE_FINDINGS) {
    textLines.push('', `...and ${findings.length - MAX_TABLE_FINDINGS} more finding(s).`);
  }

  return {
    title,
    summary,
    conclusion: blocking ? 'action_required' : 'neutral',
    text: textLines.join('\n'),
  };
}
